# file: action.yml
# version: 1.1.5
# guid: 5e6f7a8b-9c0d-1e2f-3a4b-5c6d7e8f9a0b

name: "Generate CI Test Matrices"
description: "Generate CI test matrices for Go, Python, Rust, and Node.js based on repository config"
author: "jdfalk"

branding:
  icon: "layers"
  color: "green"

inputs:
  repository-config:
    description: "Repository configuration as JSON string"
    required: false
    default: "{}"

  fallback-go-version:
    description: "Fallback Go version if not specified in config"
    required: false
    default: "1.23"

  fallback-python-version:
    description: "Fallback Python version if not specified in config"
    required: false
    default: "3.12"

  fallback-rust-version:
    description: "Fallback Rust version if not specified in config"
    required: false
    default: "1.75"

  fallback-node-version:
    description: "Fallback Node.js version if not specified in config"
    required: false
    default: "22"

  fallback-coverage-threshold:
    description: "Fallback coverage threshold if not specified in config"
    required: false
    default: "80"

  include-linux:
    description: "Include ubuntu-latest in matrix"
    required: false
    default: "true"

  include-macos:
    description: "Include macos-latest in matrix"
    required: false
    default: "false"

  include-windows:
    description: "Include windows-latest in matrix"
    required: false
    default: "false"
  use-docker:
    description: "Run inside the prebuilt Docker image"
    required: false
    default: "false"
  docker-image:
    description: "Docker image reference (tag or digest) to use when use-docker is true"
    required: false
    default: "ghcr.io/jdfalk/ci-generate-matrices-action:v1.1.5@sha256:c6a6672268cbe39f0a8ecc5b4e64124fca859f4cde6b336d26199e22be85c69e"

outputs:
  go-matrix:
    description: "Go CI matrix as JSON"
    value: ${{ steps.generate.outputs.go-matrix || steps.generate-docker.outputs.go-matrix }}

  python-matrix:
    description: "Python CI matrix as JSON"
    value: ${{ steps.generate.outputs.python-matrix || steps.generate-docker.outputs.python-matrix }}

  rust-matrix:
    description: "Rust CI matrix as JSON"
    value: ${{ steps.generate.outputs.rust-matrix || steps.generate-docker.outputs.rust-matrix }}

  frontend-matrix:
    description: "Frontend CI matrix as JSON"
    value: ${{ steps.generate.outputs.frontend-matrix || steps.generate-docker.outputs.frontend-matrix }}

  coverage-threshold:
    description: "Coverage threshold percentage"
    value: ${{ steps.generate.outputs.coverage-threshold || steps.generate-docker.outputs.coverage-threshold }}

runs:
  using: "composite"
  steps:
    - name: Generate matrices (docker)
      id: generate-docker
      if: inputs.use-docker == 'true'
      shell: bash
      env:
        REPOSITORY_CONFIG: ${{ inputs.repository-config }}
        FALLBACK_GO_VERSION: ${{ inputs.fallback-go-version }}
        FALLBACK_PYTHON_VERSION: ${{ inputs.fallback-python-version }}
        FALLBACK_RUST_VERSION: ${{ inputs.fallback-rust-version }}
        FALLBACK_NODE_VERSION: ${{ inputs.fallback-node-version }}
        FALLBACK_COVERAGE_THRESHOLD: ${{ inputs.fallback-coverage-threshold }}
        INCLUDE_LINUX: ${{ inputs.include-linux }}
        INCLUDE_MACOS: ${{ inputs.include-macos }}
        INCLUDE_WINDOWS: ${{ inputs.include-windows }}
        DOCKER_IMAGE: ${{ inputs.docker-image }}
      run: |
        set -euo pipefail

        if ! command -v docker >/dev/null 2>&1; then
          echo "::error::Docker is required when use-docker is true."
          exit 1
        fi

        touch "$GITHUB_OUTPUT" "$GITHUB_STEP_SUMMARY"

        if ! docker pull "$DOCKER_IMAGE"; then
          echo "::warning::Pull failed, building $DOCKER_IMAGE locally."
          docker build --tag "$DOCKER_IMAGE" "${{ github.action_path }}"
        fi

        docker run --rm \
          -e REPOSITORY_CONFIG \
          -e FALLBACK_GO_VERSION \
          -e FALLBACK_PYTHON_VERSION \
          -e FALLBACK_RUST_VERSION \
          -e FALLBACK_NODE_VERSION \
          -e FALLBACK_COVERAGE_THRESHOLD \
          -e INCLUDE_LINUX \
          -e INCLUDE_MACOS \
          -e INCLUDE_WINDOWS \
          -e GITHUB_OUTPUT \
          -e GITHUB_STEP_SUMMARY \
          -v "$GITHUB_OUTPUT:$GITHUB_OUTPUT" \
          -v "$GITHUB_STEP_SUMMARY:$GITHUB_STEP_SUMMARY" \
          -v "${{ github.workspace }}:/repo" \
          -w /repo \
          "$DOCKER_IMAGE"

    - name: Generate matrices
      id: generate
      if: inputs.use-docker != 'true'
      shell: bash
      env:
        REPOSITORY_CONFIG: ${{ inputs.repository-config }}
        FALLBACK_GO_VERSION: ${{ inputs.fallback-go-version }}
        FALLBACK_PYTHON_VERSION: ${{ inputs.fallback-python-version }}
        FALLBACK_RUST_VERSION: ${{ inputs.fallback-rust-version }}
        FALLBACK_NODE_VERSION: ${{ inputs.fallback-node-version }}
        FALLBACK_COVERAGE_THRESHOLD: ${{ inputs.fallback-coverage-threshold }}
        INCLUDE_LINUX: ${{ inputs.include-linux }}
        INCLUDE_MACOS: ${{ inputs.include-macos }}
        INCLUDE_WINDOWS: ${{ inputs.include-windows }}
      run: python "${{ github.action_path }}/src/generate_matrices.py"
